[package]
name = "nimage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_reflect = "0.12.1"
clap = { version = "4.5.0", features = ["derive"] }
eframe = "0.26.2"
egui_extras = { version = "0.26.2", features = ["all_loaders"] }
image = { version = "0.24.8", default-features = false, features = ["jpeg", "png"] }
jpeg-encoder = "0.6.0"
rfd = "0.13.0"
